Issue 3030 - Center aligned the text under the logos
canonical-web-and-design/snapcraft.io pull request #3097
Opened 2020-10-01 17:40 UTC by RCMainak

Fixes issue #3030. Center aligned the text under the logos in the 'how to snap an app' section on the homepage.

2020-10-01 17:40 UTC, webteam-app commented
RCMainak is not a collaborator of the repo

2020-10-01 18:03 UTC, anthonydillon requested changes
Thanks you very much for the contribution. There are two small tweaks required.

2020-10-01 18:03 UTC, anthonydillon commented on templates/partials/fsf_language.html
> +    <a class="p-card p-logo-link p-flow-lin u-align--centerk" href="/first-snap/python" data-flow-link="python">
You have an extra "k" on the `u-align--center` class

2020-10-01 18:03 UTC, anthonydillon commented on templates/partials/fsf_language.html
> +    <a class="p-logo-link p-card p-flow-lin u-align--centerk" href="/first-snap/pre-built" data-flow-link="pre-built">
You have an extra "k" on the `u-align--center` class

2020-10-01 18:05 UTC, RCMainak commented
Ops! :sweat_smile:

2020-10-02 08:20 UTC, anthonydillon approved these changes
Great, thank you very much :+1:

2020-10-02 08:20 UTC, merged

2020-10-10 16:06 UTC, RCMainak commented
Hello, if you think I have made a positive impact you can help me by adding `hacktoberfest-accepted` label to this PR. Thanks.

2020-10-10 19:39 UTC, anthonydillon commented
@RCMainak of course, thank you