Integrate cookie-policy v3.0.3
canonical-web-and-design/snapcraft.io pull request #3108
Opened 2020-10-07 14:53 UTC by anthonydillon

## Done
- Integrate cookie-policy v3.0.3
- Bump the docker image for ./run to 1.6.8
- Add link to manage tracking settings to the footer

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/3273

## QA
- Pull the branch
- Run the site using the dotrun snap with `$ dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8004/
- Check the cookie policy appears
- Check the manager opens and works
- Make a selection and the notification should disappear
- Scroll to the footer and click the Manage link in the footer
- See that manager appears again.

2020-10-07 14:53 UTC, webteam-app commented
Demo starting at https://snapcraft-io-3108.demos.haus

2020-10-08 08:07 UTC, pmahnke requested changes
just the change of the policy number

2020-10-08 08:07 UTC, pmahnke commented on package.json
> +    "@canonical/cookie-policy": "3.0.3",
should be 3.04 now

2020-10-09 19:08 UTC, anthonydillon commented
Done

2020-10-14 15:02 UTC, merged