Add search field
canonical-web-and-design/snapcraft.io pull request #3534
Opened 2021-05-07 13:41 UTC by steverydz

## Done
Added snaps search

## QA
- Go to https://snapcraft-io-3534.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps
- Click the "Add snap" button in the top right of the app
- Search for a snap (the list should appear after you have typed two characters)
- Click on any of the results and check that it is added to a list beneath the search box
- Click the bin icon in the top right of any snap in that list and check that it is removed
- Click the "Add snaps" button at the bottom of the column and check that those snaps are added to the snaps table
- Click the bin icon at the end of the table row for any snaps you have added and check that it is removed

## Issue
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/2029

2021-05-07 13:41 UTC, webteam-app commented
Demo starting at https://snapcraft-io-3534.demos.haus

2021-05-13 08:20 UTC, steverydz commented
@steverydz:

> the change to search in all stores for snaps to include is now in production (query would be something like: `/api/v2/stores/the-store-id/snaps?q=example&allowed-for-inclusion=1)`

2021-05-17 13:32 UTC, sowasred2012 requested changes
This is on Chrome & Firefox: if I search for a snap, click it and bin it, then search for another snap and click it, I see the snap I previously binned:
![search](https://user-images.githubusercontent.com/2376968/118496497-15f0c500-b71c-11eb-82ca-eed808268d0f.gif)

2021-05-17 16:20 UTC, steverydz commented
@sowasred2012 I've fixed the issue you found.

2021-05-20 10:15 UTC, tbille commented on webapp/admin/views.py
> +@admin.route("/admin/<store_id>/snaps/search")
```suggestion
@admin.route("/admin/<store_id>/snaps/search.json")
```

I like when we add the .json at then, it helps understanding what am I going to get as a return value

2021-05-20 10:16 UTC, tbille commented on static/js/public/manage-snaps.js
> +          `/admin/${STATE.store.id}/snaps/search?q=${searchField.value}&allowed_for_inclusion=${STATE.store.id}`
```suggestion
          `/admin/${STATE.store.id}/snaps/search.json?q=${searchField.value}&allowed_for_inclusion=${STATE.store.id}`
```

2021-05-20 10:22 UTC, tbille approved these changes
LGTM

2021-05-21 08:25 UTC, steverydz commented
From @danielmutis (cc @AnnSoMuller)

<img width="527" alt="Screenshot 2021-05-21 at 09 23 43" src="https://user-images.githubusercontent.com/501889/119106525-5bf8a200-ba16-11eb-9277-5665f214e669.png">

<img width="670" alt="Screenshot 2021-05-21 at 09 23 53" src="https://user-images.githubusercontent.com/501889/119106546-60bd5600-ba16-11eb-8023-afb2964ba996.png">

2021-05-21 08:44 UTC, AnnSoMuller commented
@steverydz 
Seems ok for me.

Just when I add a snap that is already there I have an error that makes me confused:
![Screenshot 2021-05-21 at 10 27 37](https://user-images.githubusercontent.com/32699582/119109039-1b525600-ba21-11eb-91be-aafecb8fce76.png)
Were other snaps well added? What was the pb etc.
Can we remove error message when uploading a snaps that is already in the list? 
It is ok to have a "success" message as the result is that the snap is in the list (of course just once)

2021-05-21 10:09 UTC, merged

2021-05-21 10:12 UTC, steverydz commented
Issue made to address the above comment https://github.com/canonical-web-and-design/snapcraft.io/issues/3551